#!/bin/bash
set -e
source /aux/emsdk/emsdk_env.sh
#
#		Download all the emulator source as is, and stop it auto running
#
cp -R ../emulator/src ../emulator/include ../emulator/framework ../emulator/6502 ../emulator/storage ../emulator/roms . -R
cp ../emulator/basic.rom storage
#
#		Build the emulator in javascript.
# 	
emcc framework/main.cpp framework/gfx.cpp framework/debugger.cpp src/sys_processor.cpp src/sys_debug_uk101.cpp src/hardware.cpp -D EMSCRIPTEN -D LINUX -D NO_DEBUGGER -DINCLUDE_OS_SUPPORT -I. -I framework -I./cpu -I./bin -I include -O2 -s USE_SDL=2 -s WASM=1 -s USE_SDL_IMAGE=2 -s SDL2_IMAGE_FORMATS='["png"]'  --preload-file storage -o f256.html
