# *******************************************************************************************
# *******************************************************************************************
#
#		Name : 		ps2codes.py
#		Purpose :	Generate PS/2 tables etc.
#		Date :		4th August 2022
#		Author : 	Paul Robson (paul@robsons.org.uk)
#
# *******************************************************************************************
# *******************************************************************************************

import re 

# *******************************************************************************************
#
#		Creates a table that maps keycodes (0-127) to the ScanCode equivalents
#
# *******************************************************************************************

rawData = open("ps2data.txt").read(-1).strip().split("\n")
keyToScan = [ "0" ] * 128

for s in rawData:
	m = re.match("^([0-9A-F]+)\\|\\|.*(SDLK_.*)$",s)
	assert m is not None,"Bad data"
	keyToScan[int(m.group(1),16)] = m.group(2).strip()


table = ",".join(keyToScan)

print("//\n//\t This file is automatically generated.\n//")
print("static int sdlKeySymbolList[] = {{ {0},-1 }};\n\n".format(table))